"""Render docs/AISVS_COVERAGE.md from the registry, the controls and the content tree.

    python -m lab.coverage_doc          # rewrite the file
    python -m lab.coverage_doc --check  # exit 1 if the committed file is stale

``tests/test_standards_registry.py`` fails when the committed file differs from this
output, so every number in it is derived, never typed.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from lab import curriculum, standards

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "AISVS_COVERAGE.md"


def _scenarios() -> list[dict]:
    rows = []
    for meta in sorted((ROOT / "content" / "areas").glob("*/scenarios/*/scenario.json")):
        d = json.loads(meta.read_text(encoding="utf-8"))
        d["_area"] = meta.parents[2].name
        rows.append(d)
    return rows


def requirement_status() -> dict[str, dict]:
    """Per cited requirement: best strength, the controls citing it, and the proofs."""
    out: dict[str, dict] = {}
    for c in curriculum.CONTROLS:
        for m in c.get("aisvs") or []:
            row = out.setdefault(m["id"], {"strength": "partial", "controls": [], "proofs": []})
            row["controls"].append(c["id"])
            if m["strength"] == "demonstrates":
                row["strength"] = "demonstrates"
                row["proofs"] += [p for p in m.get("proven_by") or [] if p not in row["proofs"]]
    return out


def ast_status() -> dict[str, dict]:
    scen = _scenarios()
    out = {}
    for aid, name in standards.AST.items():
        declared = [f"`{s['_area']}/{s['id']}`" for s in scen if aid in (s.get("ast") or [])]
        if declared:
            status = "Covered"
        elif aid in standards.AST_PARTIAL:
            status = "Partial"
        else:
            status = "Not covered"
        out[aid] = {"name": name, "status": status, "scenarios": declared}
    return out


def _key(rid: str) -> tuple[int, ...]:
    return tuple(int(x) for x in rid[1:].split("."))


def render() -> str:
    req = requirement_status()
    demo = sorted((r for r, v in req.items() if v["strength"] == "demonstrates"), key=_key)
    part = sorted((r for r, v in req.items() if v["strength"] == "partial"), key=_key)
    total = sum(c["count"] for c in standards.AISVS_CHAPTERS.values())
    ast = ast_status()
    n_cov = sum(1 for a in ast.values() if a["status"] == "Covered")
    n_part = sum(1 for a in ast.values() if a["status"] == "Partial")
    lab = lambda r: f"AISVS {standards.AISVS_VERSION} {r} (L{standards.AISVS_REQUIREMENTS[r]['level']})"  # noqa: E731

    L: list[str] = []
    L += [
        "# AISVS v1.0 and Agentic Skills Top 10: what this lab lets you verify",
        "",
        "> Generated by `python -m lab.coverage_doc` from `lab/standards.py`, `lab/curriculum.py` and the",
        "> `content/areas/` tree. Do not edit by hand; `tests/test_standards_registry.py` fails if it is stale.",
        "",
        f"OWASP AISVS {standards.AISVS_VERSION} (locked) and the OWASP Agentic Skills Top 10 {standards.AST_VERSION} are",
        "both Incubator projects under CC BY-SA 4.0. This file cites ids and gives our own one-line paraphrase.",
        f"Read the requirement text itself at {standards.AISVS_URL} and {standards.AST_URL}.",
        "",
        "**Demonstrates** means a graded check in a secure-mode run shows the control holding (named below).",
        "**Partial** means a control in the lab is related but no graded check proves the requirement as written.",
        "This lab does not make anything AISVS compliant; it lets you verify the requirements listed here.",
        "",
        "## Summary",
        "",
        f"- AISVS {standards.AISVS_VERSION}: **{len(demo)} requirements demonstrated**, **{len(part)} partial**, "
        f"of {total} in the standard.",
        f"- Out of scope, by design: {', '.join(f'{c} {standards.AISVS_CHAPTERS[c]["name"]}' for c in standards.AISVS_OUT_OF_SCOPE)}.",
        f"- Agentic Skills Top 10 {standards.AST_VERSION}: **{n_cov} covered**, **{n_part} partial**, "
        f"**{len(ast) - n_cov - n_part} not covered**, of {len(ast)}.",
        "",
        "## By chapter",
        "",
        "| Chapter | Requirements | Demonstrated | Partial | Note |",
        "|---|---|---|---|---|",
    ]
    for cid, ch in standards.AISVS_CHAPTERS.items():
        d = [r for r in demo if standards.aisvs_chapter(r) == cid]
        p = [r for r in part if standards.aisvs_chapter(r) == cid]
        note = f"Out of scope. {standards.AISVS_OUT_OF_SCOPE[cid]}" if cid in standards.AISVS_OUT_OF_SCOPE else ""
        L.append(f"| {cid} {ch['name']} | {ch['count']} | {', '.join(d) or '—'} | {', '.join(p) or '—'} | {note} |")
    L += [
        "",
        "## Requirements demonstrated",
        "",
        "| Requirement | Our paraphrase | Lab controls | Proven by (graded secure-mode check) |",
        "|---|---|---|---|",
    ]
    for r in demo:
        v = req[r]
        L.append(f"| {lab(r)} | {standards.AISVS_REQUIREMENTS[r]['summary']} | {', '.join(v['controls'])} | "
                 f"{', '.join(f'`{p}`' for p in v['proofs'])} |")
    L += [
        "",
        "## Requirements partial",
        "",
        "| Requirement | Our paraphrase | Related lab controls |",
        "|---|---|---|",
    ]
    for r in part:
        L.append(f"| {lab(r)} | {standards.AISVS_REQUIREMENTS[r]['summary']} | {', '.join(req[r]['controls'])} |")
    L += [
        "",
        f"## Agentic Skills Top 10 ({standards.AST_VERSION})",
        "",
        "| ID | Name | Status | Scenarios that declare it |",
        "|---|---|---|---|",
    ]
    for aid, a in ast.items():
        extra = f" {standards.AST_PARTIAL[aid]}" if a["status"] == "Partial" else ""
        L.append(f"| {aid} | {a['name']} | {a['status']} | {', '.join(a['scenarios']) or '—'}{extra} |")
    L += [
        "",
        "## Known gap",
        "",
        "In our reading, AISVS v1.0 has no requirement that a private-labelled item is refused at external",
        "egress anywhere in a multi-agent chain (MESA INV-01, playground level 3). See",
        "`docs/research/AISVS-COMPOSITION-NOTE.md`.",
        "",
    ]
    return "\n".join(L)


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current.replace("\r\n", "\n") != text:
            print(f"{OUT} is stale; run: python -m lab.coverage_doc")
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
